name: generate snake animation

on:
  workflow_dispatch:
  schedule:
      # every 24 hours
    #- cron: "0 */24 * * *"
      # 1x month
    - cron: "1 1 1 */1 *"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # generates a snake game from a github user
      - name: generate github-contribution-grid-snake-svg
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: itsAnyTime
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
